<?php
/**
 * District Commerce
 *
 * @category    District
 * @package     Stripe
 * @author      District Commerce <support@districtcommerce.com>
 * @copyright   Copyright (c) 2015 District Commerce (http://districtcommerce.com)
 *
 */

/**
 * @see Mage_Payment_Block_Info
 */
?>

<?php

//Get payment info
$payment = $this->getInfo();

//Get order info
$order = $payment->getOrder();

//Address verification is stored in two parts (line1/zip)
$avsStatus = explode('/', $payment->getCcAvsStatus());

//Does country match?
if(isset($payment->getAdditionalInformation()['country'])) {
    if($payment->getAdditionalInformation()['country'] !== $order->getBillingAddress()->getCountry()) {
        $countryStatus = 'fail';
    } else {
        $countryStatus = 'pass';
    }
} else {
    $countryStatus = 'unavailable';
}

//Get declined orders
$delinedOrderCount = Mage::helper('stripe')->getDeclinedOrdersCount($order->getIncrementId());

?>

<i class="icon-cc-stripe"></i>

<table cellspacing="0" class="form-list">
    <tbody>
        <tr>
            <td class="label"><label><?php echo $this->__('Card Type'); ?></label></td>
            <td class="value card-type"><strong><?php echo $payment->getCcType(); ?></strong></td>
        </tr>
        <tr>
            <td class="label"><label><?php echo $this->__('Last 4 Digits'); ?></label></td>
            <td class="value"><strong><?php echo $payment->getCcLast4(); ?></strong></td>
        </tr>
        <tr>
            <td class="label"><label><?php echo $this->__('Expiry Date'); ?></label></td>
            <td class="value"><strong><?php echo $payment->getCcExpMonth() . '/' . $payment->getCcExpYear(); ?></strong></td>
        </tr>
        <tr>
            <td class="label"><?php echo $this->__('Security Checks'); ?></td>
            <td class="value">
                <ul class="security-info">
                    <li title="<?php echo $payment->getCcCidStatus(); ?>"><span><i class="icon-<?php echo $payment->getCcCidStatus(); ?>"></i> <?php echo $this->__('CVC'); ?></span></li>
                    <li title="<?php echo $avsStatus[0]; ?>"><span><i class="icon-<?php echo $avsStatus[0]; ?>"></i> <?php echo $this->__('Street'); ?></span></li>
                    <li title="<?php echo $avsStatus[1]; ?>"><span><i class="icon-<?php echo $avsStatus[1]; ?>"></i> <?php echo $this->__('Zip'); ?></span></li>
                    <li title="<?php echo $countryStatus; ?>"><span><i class="icon-<?php echo $countryStatus; ?>"></i> <?php echo $this->__('Country'); ?></span></li>
                    <?php if($delinedOrderCount > 0) : ?>
                    <li><span><i class="icon-warning"></i> <?php echo $delinedOrderCount; ?> <?php echo $this->__('previous attempts were declined'); ?></span></li>
                    <?php endif; ?>
                </ul>
            </td>
        </tr>
        <tr>
            <td class="label">&nbsp;</td>
            <td class="value">
                <a href="<?php echo Mage::helper('stripe')->getPaymentsDashboardUrl() . $payment->getLastTransId(); ?>" target="_blank"><?php echo $this->__('View payment in Stripe'); ?></a>
            </td>
        </tr>
    </tbody>
</table>
