<?php

/**
 * District Commerce
 *
 * @category    District
 * @package     Stripe
 * @author      District Commerce <support@districtcommerce.com>
 * @copyright   District Commerce (http://districtcommerce.com)
 * 
 */
?>

<link rel="stylesheet" href="/skin/frontend/base/default/css/district/stripe/styles.css">
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <input type="hidden" name="stripeToken" id="stripe-token">
  <div id="stripe-error-messages"></div>
  <ol id="stripe-new-card">
    <li>
      <label for="stripe-cc-number" class="reader-visible">Card Number</label>
      <input id="stripe-cc-number" type="tel" x-autocompletetype="cc-number" autocompletetype="cc-number" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="Card number" data-stripe="number" size="20">
    </li>
    <li class="float">
      <label for="stripe-cc-exp" class="reader-visible">Expiry Date</label>
      <input id="stripe-cc-exp" type="tel" x-autocompletetype="off" autocompletetype="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="MM / YY" size="5" data-stripe="exp">
    </li>
    <li class="float">
      <label for="stripe-cc-cvc" class="reader-visible">CVC</label>
      <input id="stripe-cc-cvc" type="tel" autocomplete="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="CVC" data-stripe="cvc" size="4" maxlength="4">
    </li>
  </ol>
</div>

<script>

Stripe.setPublishableKey('<?php echo Mage::getStoreConfig('payment/stripe/api_publishable_key'); ?>');
  
(function() {
  district.stripeCc.init();
})();
  
</script>