<?php

/**
 * District Commerce
 *
 * @category    District
 * @package     Stripe
 * @author      District Commerce <support@districtcommerce.com>
 * @copyright   District Commerce (http://districtcommerce.com)
 * 
 */
?>

<?php
$savedCards = false;

if($token = Mage::helper('stripe')->getCustomer()->getToken()) {
  $cust = Mage::helper('stripe')->retrieveCustomer($token);
  $cards = $cust->sources->data;
  
  if(sizeof($cards) > 0) {
    $savedCards = true;
  }
}

?>

<style>
  #payment_form_stripe .has-error input {
    border-color: #f00;
  }
  
  #payment_form_stripe .reader-visible {
    position: absolute;
    left: -10000px;
    top: auto;
    width: 1px;
    height: 1px;
    overflow: hidden;
  }
  
  #payment_form_stripe input[type=tel] {
    height: 37px;
    border-radius: 4px;
    padding: 0 6px 2px 6px;
    font-family: "Helvetica Neue", "Helvetica", Arial, sans-serif;
    font-size: 15px;
    box-sizing: border-box;
    background: #fff;
    border: 1px solid #cececf;
  }
  
  #payment_form_stripe ol {
    overflow: hidden;
  }
  
  #payment_form_stripe .float {
    float: left;
  }
  
  #payment_form_stripe .checkbox {
    clear: left;
  }
  
</style>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <input type="hidden" name="stripeToken" id="stripe-token">
  <div id="stripe-error-messages"></div>
  <?php if($savedCards): ?>
  <ol>
    <li>
      <label for="stripe-saved-card" class="reader-visible">Choose card</label>
      <select id="stripe-saved-card" name="stripeSavedCard">
        <?php foreach($cards as $card): ?>
        <option value="<?php echo $card->id; ?>"><?php echo $card->brand; ?> **** **** **** <?php echo $card->last4; ?></option>
        <?php endforeach; ?>
        <option value="0">New card</option>
      </select>
    </li>
  </ol>
  <?php endif; ?>
  <ol id="stripe-new-card" <?php if($savedCards): ?> style="display:none;"<?php endif; ?>>
    <li>
      <label for="stripe-card-number" class="reader-visible">Card Number</label>
      <input id="stripe-card-number" type="tel" x-autocompletetype="cc-number" autocompletetype="cc-number" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="Card number" data-stripe="number" size="20">
    </li>
    <li class="float">
      <label for="stripe-cc-exp" class="reader-visible">Expiry Date</label>
      <input id="stripe-cc-exp" type="tel" x-autocompletetype="off" autocompletetype="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="MM / YY" size="5" data-stripe="exp">
    </li>
    <li class="float">
      <label for="stripe-cc-cvc" class="reader-visible">CVC</label>
      <input id="stripe-cc-cvc" type="tel" autocomplete="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="CVC" data-stripe="cvc" size="4" maxlength="4">
    </li>
    <?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <li class="checkbox">
      <label><input type="checkbox" name="stripeSaveCard" /> Save card for future purchases</label>
    </li>
    <?php endif; ?>
  </ol>
</div>

<script>

Stripe.setPublishableKey('<?php echo Mage::getStoreConfig('payment/stripe/api_publishable_key'); ?>');
  
(function() {
  district.stripeCc.init();
})();
  
</script>