<?php

/**
 * District Commerce
 *
 * @category    District
 * @package     Stripe
 * @author      District Commerce <support@districtcommerce.com>
 * @copyright   District Commerce (http://districtcommerce.com)
 * 
 */
?>

<?php
$isStripeCustomer = false;
$savedCards = false;

//If customer exists in our Stripe table
if($token = Mage::helper('stripe')->getCustomer()->getToken()) {
  
  //Set customer flag
  $isStripeCustomer = true;
  
  //Get customer from Stripe
  $cust = Mage::helper('stripe')->retrieveCustomer($token);
  
  //Get stored cards
  $cards = $cust->sources->data;
  
  //If there are stored cards, set saved cards flag
  if(sizeof($cards) > 0) {
    $savedCards = true;
  }
}

?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <input type="hidden" name="stripeToken" id="stripe-token">
  <?php if($isStripeCustomer): ?>
  <input type="hidden" name="isStripeCustomer" value="1">
  <?php endif; ?>
  <div id="stripe-error-messages"></div>
  <?php if($savedCards): ?>
  <ol>
    <li>
      <label for="stripe-saved-card" class="reader-visible">Choose card</label>
      <select id="stripe-saved-card" name="stripeSavedCard">
        <?php foreach($cards as $card): ?>
        <option value="<?php echo $card->id; ?>"><?php echo $card->brand; ?> **** **** **** <?php echo $card->last4; ?></option>
        <?php endforeach; ?>
        <option value="0">New card</option>
      </select>
    </li>
  </ol>
  <?php endif; ?>
  <ol id="stripe-new-card" <?php if($savedCards): ?> style="display:none;"<?php endif; ?>>
    <li>
      <label for="stripe-cc-number" class="reader-visible">Card Number</label>
      <input id="stripe-cc-number" type="tel" x-autocompletetype="cc-number" autocompletetype="cc-number" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="Card number" data-stripe="number" size="20">
    </li>
    <li class="float">
      <label for="stripe-cc-exp" class="reader-visible">Expiry Date</label>
      <input id="stripe-cc-exp" type="tel" x-autocompletetype="off" autocompletetype="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="MM / YY" size="5" data-stripe="exp">
    </li>
    <li class="float">
      <label for="stripe-cc-cvc" class="reader-visible">CVC</label>
      <input id="stripe-cc-cvc" type="tel" autocomplete="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="CVC" data-stripe="cvc" size="4" maxlength="4">
    </li>
    <?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <li class="checkbox">
      <label><input type="checkbox" name="stripeSaveCard" /> Save card for future purchases</label>
    </li>
    <?php endif; ?>
  </ol>
</div>

<script>

Stripe.setPublishableKey('<?php echo Mage::getStoreConfig('payment/stripe/api_publishable_key'); ?>');
  
(function() {
  district.stripeCc.init();
})();
  
</script>